---
title: "stl_lead_inequity"
author: "Yos"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(janitor)
```

```{r}
stl_lead<-read_csv(here::here("data","stl_blood_lead.csv"))
```

```{r}
names(stl_lead)
stl_lead<-stl_lead%>%clean_names()
names(stl_lead)
```

```{r}
skimr::skim(stl_lead)
dim(stl_lead)
```

```{r}
stl_lead$name_lsad<-as.numeric(stl_lead$name_lsad)
```

```{r}
stl_lead_prop<-stl_lead%>%mutate(prop_white=stl_lead$white/stl_lead$total_pop*100)
```

```{r}
stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated, y = white)) +
  geom_point(aes(color = pct_elevated), show.legend = FALSE) +
  scale_color_gradient(low = "purple", high = "yellow") +
  theme_minimal() +
  labs(title = "STL lead",
       x = "PCT elevated",
       y = "White")
stl_lead_plot

ggsave(here::here("figs", "stl_lead_plot.png"), height = 5, width = 6)
```

```{r}
stl_plot<-ggplot(data=stl_lead_prop,aes(x=pct_elevated))+geom_histogram(aes(color="red"), show.legend = FALSE)+theme_minimal() +labs(title = "STL lead", x = "PCT elevated",y = "Count")
stl_plot

ggsave(here::here("figs", "stl_plot.png"), height = 5, width = 6)
```
